src/error.rs
fixes #39 
This PR adds an impl for std::error::Errror and the default formatter.
Only the IoError is handled since the other are types `Cow<'static, str>` (I'm not sure why they aren't just String). Let me know what you think. I am not able to test it as the changes on the master branch break a lot of things from 0.7.3.
=> Add impl of std::error::Error and default formatter

Cargo.lock, Cargo.toml, src/compression/zip.rs
This updates crates to the latest versions.
It's also an attempt to fix an issue with ZIP1 and ZIP16 compression, replacing libflate by inflate and deflate.
Libflate causes a buffer overflow access on the huffman bitfield table, inside an iterator. I don't know exactly the reason why it does happen, but the table seems that the frequency table is not generate in a proper way in some situations causing it to have less items that what was expected.
Replacing by deflate and inflate solves the overflow issue, and both are 100% rust, keeping exrs 100% rust with no FFI.
=> Fix ZIP compression

Cargo.lock, Cargo.toml, src/compression/piz/huffman.rs
Fixed the min-heap that was causing issues in some cases, when the frequencies were not ordered by frequency. This is a much more robust version and behaves the same way as the make_heap with a custom comparator.
Added some more test, with bigger buffers, and multiple calls to compress, uncompress, since before sometimes tests passed on special cases (ordered frequencies).
=> Fully working Huffman

examples/1_rgb_exr_to_png.rs, examples/2_rgba_exposure_adjust.rs, tests/roundtrip.rs
Those semicolons seems to be useless and some of them prevents compilation (rust 1.51).
=> remove unnecessary semicolons

tests/across_compression.rs
This makes test specific debugging easier.
Fix: https://github.com/johannesvollmer/exrs/issues/124
=> split compare_compression_content tests

Cargo.lock, Cargo.toml, LICENSE.md, README.md, examples/README.md
License is now `BSD-3-Clause` in `cargo.toml`. However, we're still keeping a separate license file, to provide more detailed information about the relations between the `exrs` project and the `OpenEXR` standard.
=> specify standardized license and bump crate version

Cargo.lock, Cargo.toml, src/compression/b44/mod.rs
This crate happens to be in my dependency graph thanks to `image`, bumping these dependencies to the latest allows us to get rid of some unnecessary duplications.
Also regenerated `Cargo.lock` with the latest versions even though that isn't strictly necessary when using this crate as a library.
=> Bump `half` `miniz_oxide` and `image` dependencies to the latest

src/compression/mod.rs
Massive speedups on reads across the board, with a 2x improvement on the `read_single_image_rle_all_channels` benchmark.
**Benchmarks:**
Before:
```
test read_single_image_non_parallel_zips_rgba        ... bench: 196,783,469 ns/iter (+/- 172,721)
test read_single_image_rle_all_channels              ... bench:  41,137,521 ns/iter (+/- 3,633,097)
test read_single_image_uncompressed_from_buffer_rgba ... bench:  33,522,367 ns/iter (+/- 70,401)
test read_single_image_uncompressed_rgba             ... bench:  37,435,859 ns/iter (+/- 2,202,515)
test read_single_image_zips_rgba                     ... bench:  71,419,820 ns/iter (+/- 4,860,501)
```
After:
```
test read_single_image_non_parallel_zips_rgba        ... bench: 150,670,222 ns/iter (+/- 10,422,001)
test read_single_image_rle_all_channels …
```
=> Faster, more Rusty interleaving

Cargo.toml, benches/pixel_format_conversion.rs, benches/profiling.rs, benches/read.rs
The parallel RLE read benchmark is highly unreliable, showing variance from 20 to 28 without any changes to the code.
This PR adds a single-threaded equivalent of that benchmark so that performance could be more accurately measured.
I also suggest removing the parallel version to avoid confusion in the future, but that's up to you and not included in this PR.
=> Add non-parallel RLE read benchmark

src/compression/mod.rs
This function is responsible for 55% of execution time after #173; optimizations here have a large effect on performance.
This change leverages instruction-level parallelism to speed it up.
Benchmarks before (current master):
```
test read_single_image_non_parallel_zips_rgba        ... bench: 196,783,469 ns/iter (+/- 172,721)
test read_single_image_rle_all_channels              ... bench:  41,137,521 ns/iter (+/- 3,633,097)
test read_single_image_rle_non_parallel_all_channels ... bench:  98,932,909 ns/iter (+/- 2,856,674)
test read_single_image_uncompressed_from_buffer_rgba ... bench:  33,522,367 ns/iter (+/- 70,401)
test read_single_image_uncompressed_rgba             ... bench:  37,435,859 ns/iter (+/- 2,202,515)
test read_single_image_zips_rgba                     ... bench: …
```
=> Faster `differences_to_samples`

src/compression/mod.rs
Builds upon #173, please review and merge that first.
Allocating memory is cheap, but initializing it is not. This change makes the interleaving function reuse the buffers it has allocated and initialized. On RLE image decoding this further brings down the time spent in interleaving from 15% to 5%.
=> Reuse buffers in interleaving for a small speedup

src/image/mod.rs
This lets the caller know how much memory they should allocate.
Doesn't seem to do much to address #172, but may help some users since it's part of the public API.
=> Implement size hints for `FlatSampleIterator`

benches/read.rs
- Move reading from file into a buffer out of the benchmarking loop
- Use native `f32` instead of `f16` for benchmarking reads (conversion to `f16` is slow, which adds noise, and is profiled separately already)
- Add RLE RGBA benchmarks
- Ensure all benchmarks have a parallel and non-parallel version
=> Better read benchmarks

Cargo.lock, Cargo.toml, src/compression/pxr24.rs, src/compression/zip.rs
Another stab at #179 now that zune-inflate is fuzzed and roundtrip-fuzzed on CI.
Before:
```
test read_single_image_zips_non_parallel_rgba         ... bench: 121,828,074 ns/iter (+/- 130,167)
```
After:
```
test read_single_image_zips_non_parallel_rgba         ... bench: 113,364,196 ns/iter (+/- 93,985)
```
No effect on the parallel version - apparently the main thread is the bottleneck.
=> Use zune-inflate for decompression, take 2

Cargo.toml
Notably, this eliminates a dependency on `syn` which improves compile time.
=> Don't use flume's default features

Cargo.toml
flume depends on spin-rs, and spin-rs prior to `v0.9.8` has a [concurrency bug](https://github.com/advisories/GHSA-2qv5-7mw5-j3cg)
flume updated its spin dependency in https://github.com/zesterer/flume/commit/9f67d0d2b4c57844f3b5d6ec26e6d9f4446dae93 and released that as `v0.11.0` in https://github.com/zesterer/flume/commit/ee6fe6adb98856edbda47d1cc867cbc255ff0d88
=> bump flume version for spin-rs dependency update

src/meta/header.rs
While I was fuzzing [image-rs/fuzz/fuzzer_script_exr.rs](https://github.com/image-rs/image/blob/master/fuzz/fuzzers/fuzzer_script_exr.rs), I found `an attempt to subtract with overflow` error in [meta/header.rs](https://github.com/johannesvollmer/exrs/blob/master/src/meta/header.rs#L536)
```
$ ./image /home/toka/LibAFL/crash-47a56cc2953de83d.exr 
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 3118772312
INFO: Loaded 1 modules   (571009 inline 8-bit counters): 571009 [0x56459b9db730, 0x56459ba66db1), 
INFO: Loaded 1 PC tables (571009 PCs): 571009 [0x56459ba66db8,0x56459c31d5c8), 
./image: Running 1 inputs 1 time(s) each.
Running: /home/toka/LibAFL/crash-47a56cc2953de83d.exr
thread 'OpenEXR Block Decompressor Thread #0' panicked at …
```
=> Use checked_sub/checked_div in meta/header.rs

.github/workflows/rust.yml, Cargo.toml, README.md
Fixes #230
Instead of outright failing to compile when the `exr` crate is compiled together with a crate that selects a `half` crate version outside of the `">=2.1.0, <2.3"` range, allow anything `">=2.1.0"` but suggest people how they can _opt in_ (unfortunately it's not an opt-out) of the original `1.61` MSRV.
The difference with https://github.com/johannesvollmer/exrs/commit/42a92aa4cabde3cb0562712a251d21f161171a86 is that this does not bump `rust-version = "1.70"` which would break the suggested `half = "2.1.0"` workaround. This workaround doesn't work anyway because `"2.1.0"` allows anything `">=2.1.0, <3.0.0"`. Instead the suggestion should use the version bound provided here, or an explicit `"=2.1.0"` pinned version.
=> Allow `half 2.3` (and higher) to be used while also testing a 1.61 MSRV

Cargo.toml, src/block/reader.rs, src/block/writer.rs
Two years ago the standard library's channel implementation was [switched](https://github.com/rust-lang/rust/pull/93563) to a variant of crossbeam-channel. Now that std ships a good channel implementation, there is no reason to pull in a third-party one.
This removes a lot of dependency bloat from the `image` crate:
```
│   ├── flume v0.10.9
│   │   ├── futures-core v0.3.0
│   │   ├── futures-sink v0.3.0
│   │   ├── nanorand v0.6.0
│   │   │   └── getrandom v0.2.3
│   │   │       ├── cfg-if v1.0.0
│   │   │       └── libc v0.2.133
│   │   ├── pin-project v1.0.2
│   │   │   └── pin-project-internal v1.0.2 (proc-macro)
│   │   │       ├── proc-macro2 v1.0.52
│   │   │       │   └── unicode-ident v1.0.0
│   │   │       ├── quote v1.0.26
│   │   │       │   └── proc-macro2 v1.0.52 (*)
│   │ …
```
=> Drop flume to reduce dependency footprint now that std has a good channel

src/error.rs, src/io.rs, src/meta/attribute.rs
- breaking: add 1 new variant `Attribute::Bytes`
- use smallvec to avoid small repeated allocations when reading each attribute
=> add new byte attribute and new compression method

src/compression/mod.rs, src/image/mod.rs, src/meta/attribute.rs
pixels cannot be decompressed yet, but reading the meta data of those images now works
=> add HTJ2K compression methods to meta data
